# Generated by Django 4.2.6 on 2023-10-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('estado', models.BooleanField(default=False)),
                ('tiempoEstimado', models.BooleanField(default=False)),
                ('ubicacion', models.BooleanField(default=False)),
                ('idCliente', models.BooleanField(default=False)),
            ],
        ),
    ]
