# Generated by Django 4.2.6 on 2023-10-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Javi',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
            ],
        ),
    ]
