# Generated by Django 4.2.6 on 2023-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_javi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
