
#we'll create 'urlpatterns', which is a way to define the routes or urls
from django.urls import path,include
#inside this we'll create multiple routes.
#these routes receive 3 parameters,the name of the url, the thing that 
#will be executed(we'll import the urls generated by django), 

#this module will take the list and generate all the urls 
from rest_framework import routers

from vehiculo import views
from rest_framework.documentation import include_docs_urls
router=routers.DefaultRouter()

#from the VehiculoView class, we'll create all the urls or operations.
#'vehiculo' will be the name
router.register(r'vehiculo',views.VehiculoView,'vehiculo')
urlpatterns=[
    #every route we'll start with 'api/v1'.
    #we'll include every url generated by router
    path('api/v1/',include(router.urls)),
    path('docs/', include_docs_urls(title='Vehiculo API'))
]

#this code is generating the routes(GET,POST,PUT,DELETE)
#we can test it with a rest client.